name: Scrapper Suraci 3
on:
  workflow_dispatch:
  schedule:
      - cron: '00 07 */10 * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium==4.9.0 pyvirtualdisplay numpy==1.24.3 PyPDF2 pandas==1.5.3 gspread==5.8.0 oauth2client undetected-chromedriver==3.4.6
      - name: Install xvfb
        run: sudo apt-get install xvfb
    
      - name: Running the Python (Suraci 3)
        run: python scrapper_3.py
